version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: synacktra
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synacktra -d default"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
